const fs = require("fs");
const path = require("path");

function normalizePath(value) {
  if (!value) return "";

  let pathname = String(value).trim();
  pathname = pathname.replace(/^https?:\/\/[^/]+/i, "");

  if (!pathname.startsWith("/")) {
    pathname = `/${pathname}`;
  }

  if (!pathname.endsWith("/")) {
    pathname = `${pathname}/`;
  }

  return pathname;
}

function addRedirect(redirects, seen, from, to) {
  const normalizedFrom = normalizePath(from);
  const normalizedTo = normalizePath(to);

  if (!normalizedFrom || !normalizedTo || normalizedFrom === normalizedTo) {
    return;
  }

  if (seen.has(normalizedFrom)) {
    return;
  }

  seen.add(normalizedFrom);
  redirects.push({
    from: normalizedFrom,
    to: normalizedTo
  });
}

function loadExtraRedirects() {
  const redirectsFile = path.join(__dirname, "../../content/_data/redirects.json");

  if (!fs.existsSync(redirectsFile)) {
    return [];
  }

  try {
    const extra = JSON.parse(fs.readFileSync(redirectsFile, "utf8"));
    return Array.isArray(extra) ? extra : [];
  } catch (error) {
    console.warn(`Warning: could not read ${redirectsFile}: ${error.message}`);
    return [];
  }
}

function buildRedirects(collectionApi) {
  const redirects = [];
  const seen = new Set();

  collectionApi.getAll().forEach((item) => {
    if (item.data.draft || !item.url) {
      return;
    }

    const fromPaths = item.data.redirectFrom;
    if (!fromPaths) {
      return;
    }

    const paths = Array.isArray(fromPaths) ? fromPaths : [fromPaths];
    paths.forEach((fromPath) => addRedirect(redirects, seen, fromPath, item.url));
  });

  loadExtraRedirects().forEach(({ from, to }) => addRedirect(redirects, seen, from, to));

  return redirects.sort((a, b) => a.from.localeCompare(b.from));
}

function generateNginxRedirects(redirects) {
  const lines = [
    "# Auto-generated by Eleventy. Do not edit manually.",
    "# Rebuild the site to refresh these rules.",
    ""
  ];

  redirects.forEach(({ from, to }) => {
    const fromWithSlash = normalizePath(from);
    const fromWithoutSlash = fromWithSlash.replace(/\/$/, "");
    const target = normalizePath(to);

    lines.push(`location = ${fromWithSlash} {`);
    lines.push(`    return 301 ${target};`);
    lines.push("}");

    if (fromWithoutSlash !== fromWithSlash) {
      lines.push(`location = ${fromWithoutSlash} {`);
      lines.push(`    return 301 ${target};`);
      lines.push("}");
    }

    lines.push("");
  });

  return `${lines.join("\n").trim()}\n`;
}

function writeNginxRedirects(redirects) {
  const outputPath = path.join(__dirname, "../deploy/nginx-redirects.generated.conf");
  fs.writeFileSync(outputPath, generateNginxRedirects(redirects));
  console.log(`✓ Generated nginx redirects with ${redirects.length} rules`);
}

module.exports = {
  addRedirect,
  buildRedirects,
  generateNginxRedirects,
  loadExtraRedirects,
  normalizePath,
  writeNginxRedirects
};
